name: my_dbt_project
version: '1.0'
config-version: 2

profile: my_dbt_project   # име на профила в ~/.dbt/profiles.yml

# Папки за модели
model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]

# Папки за output (schema / database)
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Конфигурация по подразбиране за всички модели
models:
  my_dbt_project:
    models:
      staging:
        +materialized: table  # staging модели да са таблици
      marts:
        +materialized: table
        +schema: TRANSFORMED   # marts модели да са таблици
      aggregated:
        +materialized: table
        +schema: AGGREGATED    # aggregated модели да са таблици
